  general.import = [
    # "~/.config/alacritty/themes/themes/ayu_dark.toml"
     "~/.config/alacritty/themes/themes/aura.toml"
  ]

# Reload this config on save
  general.live_config_reload  = true

  [env]
  TERM                        = "alacritty"

  [window]
  decorations                 = "transparent"
  decorations_theme_variant   = "Dark"
  dynamic_padding             = true
  dynamic_title               = true
  opacity                     = 0.94
  startup_mode                = "Windowed"
  title                       = "alacritty"
  blur                        = true
  resize_increments           = false
  #option_as_alt               = "OnlyLeft"

  [window.dimensions]
  columns = 0
  lines   = 0

  [window.padding]
  x = 20
  y = 20

  [scrolling]
  history = 30000

  [font]
  builtin_box_drawing = false
  size                = 15

  [font.normal]
  family = "Operator Mono"
  style  = "Book"

  [font.italic]
  family = "Operator Mono"
  style  = "Book Italic"

  [font.bold]
  family = "Operator Mono"
  style  = "Bold"

  [font.bold_italic]
  family = "Operator Mono"
  style  = "Bold Italic"

  [font.glyph_offset]
  x = 3
  y = 1

  [font.offset]
  x = 2
  y = 5
  
  [bell]
  animation = "EaseOutExpo"
  color     = "#C0C5CE"
  command   = "None"
  duration  = 0

  [selection]
  save_to_clipboard     = true
  semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

  [cursor]
  unfocused_hollow  = true
  style             = "Beam"
  vi_mode_style 	  = "None"

  [mouse]
  hide_when_typing  = true

  [terminal]
  shell = { program = "/bin/zsh", args = ["-l"] }


  [[hints.enabled]]
  command           = "xdg-open" # On Linux/BSD
  hyperlinks	      = true
  post_processing	  = true
  persist		        = false
  mouse.enabled	    = true
  binding		        = { key = "O", mods = "Control|Shift" }
  regex		          = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

  [debug]
  highlight_damage   = false
  log_level          = "Warn"
  persistent_logging = false
  print_events       = false
  render_timer       = false
