add_newline = true

[character]
success_symbol = '[↪ ](bold #ab82f5)'
error_symbol = "[ x](bold red)"
vicmd_symbol = "[ V](bold green)"

[git_status]
disabled = false

[git_commit]
commit_hash_length = 7
tag_disabled = false
only_detached = false

[battery]
disabled = true

[python]
disabled = true

[cmake]
disabled = true

[directory]
read_only = "(read only)"
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold #f5ab82"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_metrics]
disabled = false
format = '([+$added]($added_style)) ([-$deleted]($deleted_style)) '

[git_branch]
format = "[$branch]($style) "
style = "italic #ab82f5"
